# Generated by Django 4.2.1 on 2023-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('uptime_last_hour', models.IntegerField()),
                ('uptime_last_day', models.IntegerField()),
                ('uptime_last_week', models.IntegerField()),
                ('downtime_last_hour', models.IntegerField()),
                ('downtime_last_day', models.IntegerField()),
                ('downtime_last_week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('time_zone_str', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('day', models.IntegerField()),
                ('start', models.CharField(max_length=8)),
                ('end', models.CharField(max_length=8)),
            ],
        ),
    ]
